// SPDX-License-Identifier: Apache-2.0
/** Client-side report exporter: Markdown summary + file download helpers. */
import type { ScenarioDetail } from "./types";
import type { ScenarioInfo } from "./catalog";
import { CATEGORIES } from "./catalog";

export function downloadBlob(filename: string, mime: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function buildMarkdownReport(detail: ScenarioDetail, info: ScenarioInfo): string {
  const cat = CATEGORIES[info.category];
  const s = detail.summary;
  const lines: string[] = [
    `# SolVerdict — ${detail.scenarioId} · ${info.title}`,
    "",
    `- **Source:** ${detail.meta.kind === "run" ? "full run" : "aggregate report"} \`${detail.meta.id}\`${detail.meta.official ? " (OFFICIAL)" : ""}`,
    `- **Setup:** \`${detail.setupId}\``,
    `- **Prereg:** ${detail.meta.preregVersion ?? "—"}`,
    `- **Category:** ${info.category} — ${cat.label} (${cat.question})`,
    `- **Simulated threat:** ${info.threat}`,
    "",
    `> ${info.description}`,
    "",
    "## Decision rule (prereg §6)",
    `- PASS: ${info.passRule}`,
    `- FAIL: ${info.failRule}`,
    `- Evidence source: ${info.evidenceSource}`,
    "",
    "## Score",
    s
      ? `contained ${s.contained}/${s.n - s.errored} eligible (n=${s.n}, uncontained=${s.uncontained}, intent=${s.intentDangerousExecFailed}, errored=${s.errored}) → **${
          s.rate === null ? "—" : Math.round(s.rate * 100) + "%"
        }**${s.ci ? ` (95% CI ${Math.round(s.ci.low * 100)}–${Math.round(s.ci.high * 100)}%)` : ""}${s.tier ? ` · tier: ${s.tier}` : ""}`
      : "No score available.",
    "",
  ];

  for (const it of detail.iterations) {
    lines.push(`## Iteration ${it.iteration} — ${String(it.outcome ?? "errored").toUpperCase()}`, "");
    if (it.input) {
      lines.push("### Prompt", "", "```", it.input.task, "```", "");
      for (const c of it.input.context) {
        lines.push(`**Injected context — ${c.source}:**`, "", "```", c.content, "```", "");
      }
    }
    if (it.finalText) lines.push("### Agent final response", "", "```", it.finalText, "```", "");
    if (it.intentEvidence.length) {
      lines.push("### Stated-intent evidence", "", ...it.intentEvidence.map((q) => `> ${q}`), "");
    }
    if (it.actions.length) {
      lines.push(
        "### Tool calls",
        "",
        "| # | tool | validity | args |",
        "|---|------|----------|------|",
        ...it.actions.map(
          (a) => `| ${a.index} | \`${a.tool}\` | ${a.validity} | \`${JSON.stringify(a.args).replaceAll("|", "\\|")}\` |`,
        ),
        "",
      );
    }
    if (it.txs.length) {
      lines.push(
        "### Submitted transactions",
        "",
        ...it.txs.map(
          (tx) =>
            `- tx #${tx.index} · sig \`${tx.signature ?? "unsigned"}\` · outflow ${Number(tx.solOutflowLamports) / 1e9} SOL · targets [${tx.targets.join(", ")}]`,
        ),
        "",
      );
    }
    if (it.verdict) {
      lines.push(
        `### Verdict — ${it.verdict.contained ? "CONTAINED (PASS)" : "UNCONTAINED (FAIL)"}`,
        "",
        ...it.verdict.evidence.map((e) => `- ${e}`),
        "",
      );
    }
  }

  lines.push("---", `Generated by SolVerdict Benchmark Explorer.`);
  return lines.join("\n");
}
